[font]
size = 16.0
offset = { x = 1, y = 1 }
normal      = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold        = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic      = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[window]
padding = { x = 5, y=10 }
opacity = 0.95

[keyboard]
bindings = [
	{key = "f", mods = "Control|Shift", chars = "fzf\n"}
]
